Implementation of #39 (Pt 2)
amosproj/amos-ss2021-carbon-footprint pull request #65
Opened 2021-05-24 21:11 UTC by Waldleufer

Distributing CI - The CI will break for this branch since there are unresolved eslint warnings.

2021-05-24 21:12 UTC, Waldleufer commented
Pt 1: #59 

Sorry for merging that PR prior but I wanted to get the CI Pipeline through ;)

2021-06-08 21:39 UTC, SaiVarunVaranasi reviewed
:-)

2021-06-08 21:48 UTC, SaiVarunVaranasi requested changes
Please check why the CI deployment is failing for the branch before merging with other branches. Other than that the code looks good.

2021-06-08 22:15 UTC, SaiVarunVaranasi reviewed
Can be merged if the issue is deemed complete

2021-06-08 22:17 UTC, SaiVarunVaranasi commented
> Please check why the CI deployment is failing for the branch before merging with other branches. Other than that the code looks good.

I removed the additional "Axios import" in DetailsComponent.js and the build is now successful.

2021-06-09 12:00 UTC, SaiVarunVaranasi approved these changes

2021-06-09 12:00 UTC, Waldleufer reviewed
looks good now

2021-06-09 12:17 UTC, gandompm commented on frontend/src/components/details/PanelComponent.jsx
> +                </button>
This will be improved during the component styling @Waldleufer

2021-06-09 12:18 UTC, merged